### ISSUE TITLE
How to make it work with existing chrome profile??

### ISSUE THREAD

**Issue by RLuckyX** [markmelnic/stealthenium#4]
This is my start function which starts existing chrome profile using remote debugging and than connect driver to that profile i tried different ways to make it work with existing profile but failed to do so Please help me to modify this function so that it works on existing profile rather than opening new profile

And also want to ask whether we need to feed pool of UAs, vendor etc.. or it has everything already
If anything seems like silly question sorry for that i am still beginner in this thing

`
def start_chrome(profile, port, proxy_config):
    proxy_extension = create_extension(
        proxy_config["username"],
        proxy_config["password"],
        proxy_config["host"],
        proxy_config["port"])

    chrome_options = Options()
    chrome_options.add_argument(f'--remote-debugging-port={port}')
    chrome_options.add_argument(f'--profile-directory={profile}')
    chrome_options.add_argument('--no-first-run')
    chrome_options.add_argument('--no-default-browser-check')
    cmd = [
        "chrome.exe",
        *chrome_options.arguments,
        f"--load-extension={proxy_extension}",
    ]

    try:
        process = subprocess.Popen(cmd, shell=True)
        service = Service(ChromeDriverManager().install())
        chrome_options.add_experimental_option('debuggerAddress', f'localhost:{port}')
        driver = webdriver.Chrome(service=service, options=chrome_options)
        print(f"Chrome started with profile: {profile}, port: {port}")
        return process, driver
    except Exception as e:
        print(f"Error starting Chrome with proxy: {e}")
        return None, None`

**Comment by markmelnic** [comment]
I think this is not the right place for this question as it seems unrelated to this repository. Go to [selenium repo](https://github.com/SeleniumHQ/selenium) or try [this answer](https://github.com/SeleniumHQ/selenium).

**Comment by RLuckyX** [comment]
> I think this is not the right place for this question as it seems unrelated to this repository. Go to [selenium repo](https://github.com/SeleniumHQ/selenium) or try [this answer](https://github.com/SeleniumHQ/selenium).

Brother I can do that using remote debugging but it needs to patch that chrome webdriver with stealth to use that stealth feature thats why i asked is there any way to patch profile which is opened using remote debugging first and than we connect it with webdriver using debuggeraddress and port >

also you provided same link in both selenium repo and this answer
